services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: